### ISSUE TITLE
It blocks the browser

### ISSUE THREAD

**Issue by yeban** [wurmlab/genevalidatorappAPI#3]
Use of `async: false` in `$.ajax` causes the browser tab from which `sendToGV` was called to block - can't even scroll - till the ajax request has completed. This is fine for demo, but unusable as an extension from another app.

Should either take a callback, or return a promise instead.

**Comment by IsmailM** [comment]
Fixed…

Uses a Promise...

See [demo here](http://wurmlab.github.io/GeneValidatorApp-API/)
