### ISSUE TITLE
Open in a new tab by default.

### ISSUE THREAD

**Issue by yeban** [wurmlab/genevalidatorappAPI#4]
The API currently returns a link. I think the API should open the result in a new tab by default. And could allow to get a link instead, if for example I want to open the result in an iframe instead.

**Comment by IsmailM** [comment]
Fixed…

It is possible to obtain the results url or JSON url as well (it is currently written to the console and returned)..

See [demo here](http://wurmlab.github.io/GeneValidatorApp-API/)
